# Generated by Django 5.2.7 on 2025-12-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_publishaed_date_post_published_date_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('posts', models.ManyToManyField(blank=True, related_name='tags', to='blog.post')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
